export const listCargos = [
  { id: 15, name: 'Coronel' },
  { id: 14, name: 'Tenente-Coronel' },
  { id: 13, name: 'Major' },
  { id: 12, name: 'Capitão' },
  { id: 11, name: '1º Tenente' },
  { id: 10, name: '2º Tenente' },
  { id: 9, name: 'ASP. A OF.' },
  { id: 8, name: 'Sub-Tenente' },
  { id: 7, name: '1º Sargento' },
  { id: 6, name: '2º Sargento' },
  { id: 5, name: '3º Sargento' },
  { id: 4, name: 'Cabo' },
  { id: 3, name: 'Soldado' },
  { id: 2, name: 'AL CFO' },
  { id: 1, name: 'AL CFP' },
]
